import { useStore } from '@/lib/store'
import { cn, formatDate } from '@/lib/utils'
import { FileText, CheckCircle2, AlertTriangle, ArrowRight, Sparkles, Calendar } from 'lucide-react'

export function WeeklyReportPage() {
  const reports = useStore((s) => s.reports)
  const projects = useStore((s) => s.projects)

  const report = reports[0]
  const project = report ? projects.find((p) => p.id === report.projectId) : null

  if (!report || !project) {
    return (
      <div className="flex items-center justify-center h-full text-text-muted text-[13px]">
        No reports available
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-[1000px] p-6 animate-fade-in">
      <div className="mb-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-bg-elevated">
            <FileText size={16} className="text-text-secondary" />
          </div>
          <div>
            <h1 className="text-lg font-semibold text-text-primary">Weekly Report</h1>
            <p className="text-[12px] text-text-muted">Auto-generated by AI — {project.name}</p>
          </div>
        </div>
        <div className="flex items-center gap-2 rounded-md border border-border-subtle bg-bg-surface px-3 py-1.5">
          <Calendar size={12} className="text-text-muted" />
          <span className="text-[12px] text-text-secondary font-mono">
            {formatDate(report.weekStart)} — {formatDate(report.weekEnd)}
          </span>
        </div>
      </div>

      <div className="rounded-lg border border-border-subtle bg-bg-surface mb-4">
        <div className="flex items-center gap-2 border-b border-border-subtle px-4 py-2.5">
          <span className="text-[12px] font-medium text-text-secondary">Summary</span>
          <Sparkles size={11} className="text-accent-ai ml-auto animate-pulse-ai" />
          <span className="text-[10px] text-text-muted">AI Generated</span>
        </div>
        <div className="p-4">
          <p className="text-[13px] text-text-secondary leading-relaxed">{report.summary}</p>
          <div className="mt-4 flex gap-4">
            <div className="flex items-center gap-2 rounded bg-success-dim px-3 py-1.5">
              <CheckCircle2 size={12} className="text-success" />
              <span className="text-[12px] text-success font-mono">{report.completedTasks}/{report.totalTasks}</span>
              <span className="text-[11px] text-text-muted">tasks completed</span>
            </div>
            <div className="flex items-center gap-2 rounded bg-accent-primary/10 px-3 py-1.5">
              <span className="text-[12px] text-accent-primary font-mono">{Math.round((report.completedTasks / report.totalTasks) * 100)}%</span>
              <span className="text-[11px] text-text-muted">completion rate</span>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        <ReportSection
          title="Highlights"
          icon={CheckCircle2}
          color="text-success"
          items={report.highlights}
        />
        <ReportSection
          title="Risks"
          icon={AlertTriangle}
          color="text-warning"
          items={report.risks}
        />
        <ReportSection
          title="Next Week"
          icon={ArrowRight}
          color="text-accent-primary"
          items={report.nextWeekPlan}
        />
      </div>

      <div className="mt-4 text-center">
        <span className="text-[10px] text-text-muted">
          Generated at {new Date(report.generatedAt).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}
        </span>
      </div>
    </div>
  )
}

function ReportSection({ title, icon: Icon, color, items }: { title: string; icon: React.ElementType; color: string; items: string[] }) {
  return (
    <div className="rounded-lg border border-border-subtle bg-bg-surface">
      <div className="flex items-center gap-2 border-b border-border-subtle px-4 py-2.5">
        <Icon size={13} className={color} />
        <span className="text-[12px] font-medium text-text-secondary">{title}</span>
        <span className="ml-auto text-[10px] font-mono text-text-muted">{items.length}</span>
      </div>
      <div className="p-3 space-y-2">
        {items.map((item, i) => (
          <div key={i} className="flex items-start gap-2">
            <span className={cn('mt-1.5 h-1 w-1 shrink-0 rounded-full', color.replace('text-', 'bg-'))} />
            <span className="text-[12px] text-text-secondary leading-relaxed">{item}</span>
          </div>
        ))}
      </div>
    </div>
  )
}
